version: '3.7'
services:
  
  #===================================================
  # SERVER MARIADB
  #===================================================
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MARIADB_DATABASE: doador
      MARIADB_USER: user
      MARIADB_PASSWORD: 1234567
      MARIADB_ROOT_PASSWORD: 1234567
    ports:
      - 3307:3306
    volumes:
      - ./.data/mariadb/data:/var/lib/mariadb
    networks:
      - dev-network
  #===================================================
  # SERVER front
  #===================================================
  frontend:
    image: nginx:latest
    container_name: nginx
    ports: 
      - 8080:80
    volumes:
      - ./front:/usr/share/nginx/html
    networks:
      - dev-network
  #===================================================
  # SERVER api
  #===================================================
  #api:
  #  image: projigreja/api
  #  container_name: api
  #  entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
  #  volumes:
  #    - ./api:/usr/src/app
  #  tty: true
  #  networks:
  #    - dev-network
  #  depends_on:
  #    - db
  #===================================================
  # SERVER PHPMYADMIN
  #===================================================

#===================================================
# NETWORK
#===================================================
networks:
  dev-network:
    driver: bridge