version: '3.7'
services:
  
  #===================================================
  # SERVER MARIADB
  #===================================================
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MARIADB_DATABASE: doador
      MARIADB_USER: user
      MARIADB_PASSWORD: 1234567
      MARIADB_ROOT_PASSWORD: 1234567
    ports:
      - 3307:3306
    volumes:
      - ./.data/mariadb/data:/var/lib/mariadb
    networks:
      - dev-network
  #===================================================
  # SERVER PHPMYADMIN
  #===================================================

#===================================================
# NETWORK
#===================================================
networks:
  dev-network:
    driver: bridge